#!/bin/env python2

key = "ICE"
text = """
Burning 'em, if you ain't quick and nimble
I go crazy when I hear a cymbal
""".strip()
encrypted = ""
for i in range(len(text)):
    encrypted += chr(ord(text[i]) ^ ord(key[i % len(key)]))

print encrypted.encode('hex')
