#!/bin/env python2
from Crypto.Util.strxor import strxor

def xor(s1, s2):
    if len(s1) != len(s2):
        print "xor(s1,s2): Strings aren't same length"
        exit()

    s1 = s1.decode('hex')
    s2 = s2.decode('hex')
    s3 = [chr(ord(x) ^ ord(y)) for (x,y) in zip(s1,s2)]



    return "".join(s3).encode('hex')

s1 = b'1c0111001f010100061a024b53535009181c'
s2 = b'686974207468652062756c6c277320657965'
print xor(s1,s2)

print strxor(s1.decode('hex'),s2.decode('hex')).encode('hex')



